name: CI

# Déclenche le pipeline lors des push et pull requests sur la branche principale
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    # Utilise une machine virtuelle Ubuntu pour exécuter le pipeline
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      # Vérifie le code source depuis le dépôt GitHub
      uses: actions/checkout@v3

    - name: Setup Node.js
      # Configure l'environnement Node.js avec la version spécifiée
      uses: actions/setup-node@v3
      with:
        node-version: '20.18.0'

    - name: Setup Ionic
      # Installe Ionic et ses dépendances
      run: |
        npm install -g ionic@7.2.0

    - name: Verify Ionic Installation
      # Verifie l'installation d'Ionic
      run: ionic --version

    - name: Cache Node modules
      # Cache les dépendances npm pour accélérer les builds
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - name: Install dependencies
      # Installe les dépendances du projet à partir du fichier package.json
      run: npm install

    - name: Lint
      # Exécute la vérification du code pour s'assurer qu'il respecte les standards de codage
      run: npm run lint

    - name: Build
      # Compile le projet Ionic/Angular
      run: npm run build

    - name: Test
      # Exécute les tests unitaires pour vérifier que le projet fonctionne correctement
      run: npm test -- --watch=false --bail

    - name: Notify failure
      if: failure()
      run: echo "Build or tests failed. Please check the logs."
