name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.18.0'

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Setup Ionic
        run: npm install -g ionic@latest

      - name: Setup Angular CLI
        run: npm install -g @angular/cli@latest

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm install

  lint:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm install

      - name: Setup Angular CLI
        run: npm install -g @angular/cli@latest

      - name: Lint
        run: npm run lint

  build:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm install

      - name: Setup Angular CLI
        run: npm install -g @angular/cli@latest

      - name: Build
        run: npm run build

  test:
    runs-on: ubuntu-latest
    needs: [ lint, build ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm install

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.18.0'

      - name: Setup Angular CLI
        run: npm install -g @angular/cli@latest

      - name: Initialize Firebase
        run: |
          echo "const { initializeApp } = require('firebase/app');
            const firebaseConfig = {
              apiKey: 'AIzaSyAtTadiTbfsVqRAK1fxolhABxc4gAJHKAI',
              authDomain: 'rent-car-administrator.firebaseapp.com',
              projectId: 'rent-car-administrator',
              databaseURL: 'https://rent-car-administrator-default-rtdb.europe-west1.firebasedatabase.app/',
              storageBucket: 'rent-car-administrator.appspot.com',
              messagingSenderId: '943999344997',
              appId: '1:943999344997:web:15ff3ff6f0dc0e5a9a018c'
            };
            initializeApp(firebaseConfig);" > firebase-init.js

      - name: Provide ActivatedRoute
        run: |
          echo "import { TestBed } from '@angular/core/testing';
          import { RouterTestingModule } from '@angular/router/testing';
          import { ActivatedRoute } from '@angular/router';
          import { of } from 'rxjs';
          TestBed.configureTestingModule({
            imports: [RouterTestingModule],
            providers: [
              { provide: ActivatedRoute, useValue: { params: of({}) } }
            ]
          });" > provide-activatedroute.js

      - name: Test
        run: npm test -- --watch=false --browsers=ChromeHeadlessCI

      - name: Notify failure
        if: failure()
        run: echo "Build or tests failed. Please check the logs."
