name: CI

# Déclenche le pipeline lors des push et pull requests sur la branche principale
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.18.0'

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Setup Ionic
        run: npm install -g ionic@latest

      - name: Setup Angular CLI
        run: npm install -g @angular/cli

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm install

  lint:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Lint
        run: npm run lint

  build:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.18.0'

      - name: Setup Angular CLI
        run: npm install -g @angular/cli

      - name: Build
        run: npm run build

  test:
    runs-on: ubuntu-latest
    needs: [ lint, build ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.18.0'

      - name: Setup Angular CLI
        run: npm install -g @angular/cli

      - name: Test
        run: npm test -- --watch=false --bail

      - name: Notify failure
        if: failure()
        run: echo "Build or tests failed. Please check the logs."
